# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Enable mouse support in tmux
set -g mouse on

# Preserve custom window names
set -g allow-rename off
set -g automatic-rename off
set -g set-titles off 

# Increase scrollback buffer size
set -g history-limit 100000

# Set a custom prefix to avoid conflicts with fzf bindings (default C-b)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Enable 256 colors
set -g default-terminal "tmux-256color"

# Catppuccin Mocha theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_date_time_text " %H:%M  %d-%b"

run ~/.dotfiles/vendor/catppuccin-tmux/catppuccin.tmux

# Status bar configuration
set -g status-bg "#11111b"
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory} #{E:@catppuccin_status_date_time} #{E:@catppuccin_status_session}"
