# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)" # for vi mode if you use it

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 0       # don’t cut off after N segments
truncate_to_repo = false    # don’t stop at the repo root
fish_style_pwd_dir_length = 0  # don’t shorten each segment

[git_status]
stashed = "="
behind = "↓"

[status]
style = "bold red"
symbol = "✘ "
disabled = false
