name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * 5"  # Every Friday at 20:00

permissions:
  contents: read

jobs:
  install:
    name: Install
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Run install
      run: make install
